### ISSUE TITLE
提问：右边的函数列表是怎么弄出来的？

### ISSUE THREAD

**Issue by muyuuuu** [krisfans/nvim#3]
就是下面这张图片右边的函数列表是怎么弄出来的？

![](https://raw.githubusercontent.com/krisfans/nvim/coc/fig/program.png)

我看你用了 vim 和 neovim，这俩体验感有什么区别吗？我用的是 vim，但感觉有些朴素，spacevim 又有点臃肿的感觉。另外，我也是西电的。

**Comment by krisfans** [comment]
哈哈，校友。右边函数列表的插件是[vista.vim](https://github.com/liuchengxu/vista.vim)。vim和neovim的感觉还是neovim好一点，新特性基本是neovim这边先开发，然后才有vim跟进的，个人主要使用的是nvim。
